### ISSUE TITLE
download v1.3.1 failed

### ISSUE THREAD

**Issue by hzxuzhonghu** [prometheus/prom2json#116]
```
$ go get  github.com/prometheus/prom2json@v1.3.1
go: downloading github.com/prometheus/prom2json v1.3.1
verifying github.com/prometheus/prom2json@v1.3.1: checksum mismatch
        downloaded: h1:7+kNt7FSQFjppCuTlgg4/QVMIo6vS4oqByCvb4ePuXc=
        go.sum:     h1:OogL5hsrJpLPz3jZ4LPz4sJRTtADzViCNRQoqrzUQvk=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by beorn7** [comment]
If I do the `go get github.com/prometheus/prom2json@v1.3.1` right now, I get the checksum from your `go.sum`. It seems your `go get` attempt above has downloaded a corrupted version.

Maybe try `go clean -modcache` and then `go get` it again and see if the problem persists?

In any case, this looks like a problem on your side or with whatever source you are downloading the module from, but not in the GH repository itself.

**Comment by hzxuzhonghu** [comment]
After i changed a GOPROXY, then i can successfully download it

**Comment by liuguangwei** [comment]
I happend an same problem , can you tell me  what is your  GOPROXY
