### ISSUE TITLE
Add support for installation via homebrew

### ISSUE THREAD

**Issue by cjappl** [prometheus/prom2json#130]
Just discovered this, and it already seems super useful.

It'd be nice if it was install-able via popular package managers like `brew` and `apt-get` etc. May help encourage adoption!

**Comment by beorn7** [comment]
Sure, but that's a task for the distributors. There is nothing to do here in this repository, is it? (If anything in here makes life for distributors harder than necessary, please let me know.)

**Comment by beorn7** [comment]
@NightTsarina maybe you have context why prom2json isn't included in any Debian package? (Or maybe it is, and I just haven't found it?)

**Comment by NightTsarina** [comment]
@beorn7 I think I did not know about this tool. Now we are late in the release cycle to include this in bookworm, but I would like to include it soon..

Thanks for the heads up!

**Comment by beorn7** [comment]
Thanks @NightTsarina . That settles Debian.

@cjappl if you have any contacts into Homebrew, feel free to encourage them to package this tool.

I'll close this for now. Btu feel free to follow up if there are any blockers in the repo that makes packaging harder than necessary.
