### ISSUE TITLE
Unable to execute from exec.Command

### ISSUE THREAD

**Issue by spirrello** [prometheus/prom2json#26]
Hi,

I'm trying to leverage prom2json for scraping metrics from k8s-state-metrics and I have simple prototype but the following code keeps failing with "exit status 1".  I'm unsure if this is a prom2json issue or something in my syntax.

package main

import (
	"fmt"
	"log"
	"os/exec"
)

func main() {

	args := []string{"http://10.157.101.172:8080/metrics|jq", "'.[]|select(.name==\"kube_node_spec_unschedulable\")[\"metrics\"][][\"value\"]'"}
	fmt.Printf("%v", args)
	cmd := exec.Command("./prom2json", args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		log.Fatalf("cmd.Run() failed with %s\n", err)
	}
	fmt.Printf("combined out:\n%s\n", string(out))

}

**Comment by beorn7** [comment]
You are using a pipe within an argument (`"http://10.157.101.172:8080/metrics|jq"`). Pipes are a Unix shell feature, not something that the `prom2json` binary would handle as part of argument processing.

This is definitely about how to run shell command with `os/exec`, not about `prom2json`.
