### ISSUE TITLE
support passing custom headers to HTML

### ISSUE THREAD

**Issue by akostadinov** [prometheus/prom2json#28]
Would be good to support adding custom headers for http request to allow bearer token auth.

**Comment by akostadinov** [comment]
If all the tool does is to read a http url and parse content, then what you say makes sense.

**Comment by beorn7** [comment]
Let's wait for #35 to be ready, and then you can try out if a pipe with `curl` covers your use case.

**Comment by beorn7** [comment]
Works fine for me. I'll close this. Please follow up if there are issues with the approach.
