### ISSUE TITLE
FetchMetricFamilies could hang the call

### ISSUE THREAD

**Issue by yiminc** [prometheus/prom2json#71]
This code needs to setup a proper timeout, otherwise it could hang forever. 
We have one incident where the call to client.Do() never returns.
https://github.com/prometheus/prom2json/blob/master/prom2json.go#L157

**Comment by yiminc** [comment]
The stack relevant call stack is:

#	0x7fd71b	net/http.(*persistConn).roundTrip+0x75b						GOROOT/src/net/http/transport.go:2194
--
#	0x7f2e0a	net/http.(*Transport).roundTrip+0xa1a						GOROOT/src/net/http/transport.go:481
#	0x7d8ea4	net/http.(*Transport).RoundTrip+0x34						GOROOT/src/net/http/roundtrip.go:17
#	0x79d910	net/http.send+0x460								GOROOT/src/net/http/client.go:250
#	0x79d30a	net/http.(*Client).send+0xfa							GOROOT/src/net/http/client.go:174
#	0x79e918	net/http.(*Client).do+0x278							GOROOT/src/net/http/client.go:641
#	0xffffea	net/http.(*Client).Do+0x2ca							GOROOT/src/net/http/client.go:509
#	0xffffd4	github.com/prometheus/prom2json.FetchMetricFamilies+0x2b4			external/com_github_prometheus_prom2json/prom2json.go:156
....

**Comment by beorn7** [comment]
My suspicion is this is because we are building our own `http.Transport` here: https://github.com/prometheus/prom2json/blob/master/cmd/prom2json/main.go#L117

This transport has no timeouts set, different from the `http.DefaultTransport`.

I think this is easy to fix. Stay tuned…

**Comment by beorn7** [comment]
OK, #72 might fix your issue. Please have a look.

As said there, this now uses the default transport, which has a few timeouts and such set. It also additionally sets a timeout for the initial headers. There are, however, still scenarios where the tool will hang for very long (or even forever). I don't want to be too aggressive with something like a timeout for the total scrape time, as that would need to be configurable. The decision a while ago was to leave advanced settings to `curl`, which you can use to fetch the metrics and then simply pipe it into `prom2json`, see https://github.com/prometheus/prom2json#usage .
