### ISSUE TITLE
Installation fails with last commit

### ISSUE THREAD

**Issue by zamir0109** [prometheus/prom2json#74]
Hi!

With the last commit the installation of this package is failing.

### Details:
- Command used: go get github.com/prometheus/prom2json/cmd/prom2json
- Environment: docker
- Docker image: fluent/fluentd:v1.7-1
- Error output: 

```
go/src/github.com/prometheus/prom2json/cmd/prom2json/main.go:108:54: http.DefaultTransport.(*http.Transport).Clone undefined (type *http.Transport has no field or method Clone)
```
Go version: go1.11.5 linux/amd64

However tried installing outside of docker and the error is the same.

Thanks!

**Comment by beorn7** [comment]
You need at least Go 1.13 to compile prom2json, see [go.mod](https://github.com/prometheus/prom2json/blob/master/go.mod#L13).

We also offer [ready-built binaries to download](https://github.com/prometheus/prom2json/releases).

**Comment by zamir0109** [comment]
Thank you so much
