### ISSUE TITLE
Readme Docker Link

### ISSUE THREAD

**Issue by Setheck** [prometheus/prom2json#80]
The readme under `Using Docker` has the following text

`You can deploy this tool using the [prom/prom2json](https://registry.hub.docker.com/u/prom/prom2json/) Docker image.`

However, the link to docker hub seems incorrect. I believe it should be 

`You can deploy this tool using the [prom/prom2json](https://registry.hub.docker.com/r/prom/prom2json/) Docker image.`

**Comment by beorn7** [comment]
I guess you are right. Please have a loot at #81.

**Comment by Setheck** [comment]
Nothing like a 1 character change :grin:
