### ISSUE TITLE
prom2json doesn't produce valid json with node-exporter enabled

### ISSUE THREAD

**Issue by black3806** [prometheus/prom2json#85]
[node-exporter.json.txt](https://github.com/prometheus/prom2json/files/5531141/node-exporter.json.txt)

Parse error on line 1:
...es"},"value":"51"}]},{"name":"go_gc_dura
-----------------------^
Expecting 'EOF', got ','

**Comment by beorn7** [comment]
The example fail is just missing a leading `[`. Are you sure this is coming directly out of `prom2json`? Perhaps something else is eating the first character of the output somehow?

**Comment by black3806** [comment]
let me double check that

**Comment by beorn7** [comment]
Assuming that was the case. Please reopen if needed.
