### ISSUE TITLE
Can't install using 'go install'

### ISSUE THREAD

**Issue by orkenstein** [prometheus/prom2json#96]
I'm trying to install using `go version go1.17.1 darwin/amd64`:

```
$ go install github.com/prometheus/prom2json/cmd/prom2json@latest -v
go install: -v: all arguments must have the same version (@latest)
```

Looks like it isn't successful:
```
$ which prom2json
prom2json not found
```

**Comment by beorn7** [comment]
You have to leave out the `-v`. 

The following should just work
```
$ go install github.com/prometheus/prom2json/cmd/prom2json@latest
```

**Comment by beorn7** [comment]
You have to leave out the `@version` if you are in GOPATH mode.

WRT to the `prom2json not found`: I assume you haven't set up your PATH to include where Go installs binaries.

From `go help install`:

```
Executables are installed in the directory named by the GOBIN environment
variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH
environment variable is not set. Executables in $GOROOT
are installed in $GOROOT/bin or $GOTOOLDIR instead of $GOBIN.
```

I should note that none of this is specific to prometheus/prom2json. This is all just how the `go` command works. So you might find better help to troubleshoot your issue in general Go community channels.
